language: node_js
sudo: false
node_js:
  - 6
  - 7

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install coveralls

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run coveralls

before_deploy:
  - npm run product

deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email: qowera@qq.com
  api_key:
    secure: Uno6+uf4EqbsdqLmLrUqCOBxw/ykfjxv9OSTcFRISzeajAE4e/HG3sYx+V+pr7IeaODafl7KVX60gIxT92II9Z08EpMrQp5G0C6Jm0qof1ECSosgXm9b8Tr2JG9GnJxgABUMw0FlfxrSK1Pa0kE21eOZxzW0s+p7Sb91z+EBUrOjfvmp3pt3flru9klCnOrm89OjlWJ++1+Ifeu5Nc1b9QvotaL8EcnIZP5Z9kmP3Ai2CcTnfP+6PMANGZzrVpWlWX8OgeYze5z3OTc5ROfwk/cDbAJ1YiKXeyxbCGiBfjSrGY/TGV/5UE6+oMKRfVKejVgOSKvBfunfhVv8yhhbSIS6Y90hayYC2tLtk97jmXdorJc1Tq5sdnPyC0wb7gO242YvQSN05pSwRuGfuxtdEzqRTu9QULeaQsQtqPH4kMi35mB2PRd5JqEvrW5AquaPQ9g8MI9DOUmPp5xt1JeWHEpYIcKDlM33iZffritkyKXOUxjivyjm1S7s5yjhKVuB2LGLeauce9iMer7g+Ogtm46RbHtROG+6tjp7kfSEqn9QT7Zguei/929hWqfozKtXbBBlx9/Eomz1hR5fA9GRBbagytlvuLGvuWVuC8IPjy1snjhHsaKfH1J6T6a9KIb3zVc/wHRP9J5FsxEkKesxLWpjSdU3r3Pi/F+uqcWa9ec=
